// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-m-5dz-kE8eHcSQoLPJ0uY-_w60sdP_o',
    appId: '1:235933559980:web:415d3cafd0543a77b70309',
    messagingSenderId: '235933559980',
    projectId: 'khaikhai-bc14a',
    authDomain: 'khaikhai-bc14a.firebaseapp.com',
    storageBucket: 'khaikhai-bc14a.firebasestorage.app',
    measurementId: 'G-DXFKBHFM2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_fkMpFGuDdWHYNj2bPVdD6_5ayNEESCk',
    appId: '1:235933559980:android:319b22fe7095659eb70309',
    messagingSenderId: '235933559980',
    projectId: 'khaikhai-bc14a',
    storageBucket: 'khaikhai-bc14a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNow8bJCNGv4KRoSauMb9xfLC1RNm-LY4',
    appId: '1:235933559980:ios:6bf8af321466b954b70309',
    messagingSenderId: '235933559980',
    projectId: 'khaikhai-bc14a',
    storageBucket: 'khaikhai-bc14a.firebasestorage.app',
    iosBundleId: 'com.example.khaikhai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNow8bJCNGv4KRoSauMb9xfLC1RNm-LY4',
    appId: '1:235933559980:ios:6bf8af321466b954b70309',
    messagingSenderId: '235933559980',
    projectId: 'khaikhai-bc14a',
    storageBucket: 'khaikhai-bc14a.firebasestorage.app',
    iosBundleId: 'com.example.khaikhai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-m-5dz-kE8eHcSQoLPJ0uY-_w60sdP_o',
    appId: '1:235933559980:web:d1d75e7b38e13822b70309',
    messagingSenderId: '235933559980',
    projectId: 'khaikhai-bc14a',
    authDomain: 'khaikhai-bc14a.firebaseapp.com',
    storageBucket: 'khaikhai-bc14a.firebasestorage.app',
    measurementId: 'G-J7SPEYPG9G',
  );
}
